### ISSUE TITLE
[BUG] Installation Problem on WSL (Windows)

### ISSUE THREAD

**Issue by girirajvengurlekar** [Privado-Inc/privado#39] opened 2022-08-25 12:15 UTC
**Describe the bug**
Unable to install privado on a Ubuntu instance using wsl

**To Reproduce**
1. Open cmd on windows
2. wsl -d Ubuntu
3. curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3504  100  3504    0     0   8443      0 --:--:-- --:--:-- --:--:--  8423

**Comment by ojaswa1942** [comment] 2022-09-01 13:10
Hi @girirajvengurlekar 
I notice that the output from the third command is incomplete. Can you please share the full output along with the WSL version?

**Comment by SandhyaBaskaran** [comment] 2022-09-07 06:09
Hi . Im also facing the same issue. Unable to install on mac.
curl -o- https://raw.githubusercontent.com/Privado-Inc/privado/main/install.sh |bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0      9      0  0:00:01  0:00:01 --:--:--     9
bash: line 1: 404:: command not found

**Comment by ojaswa1942** [comment] 2022-09-07 06:21
Hi @SandhyaBaskaran,
In your case, it seems like the installation URL is incorrect. Please use this instead and feel free to get back in case of any further issues:
```
curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
```

Can you also point us to the reference for the installation command you used? We will be happy to fix that immediately.

**Comment by SandhyaBaskaran** [comment] 2022-09-07 06:46
Yes this is working. This installation command was found in getting-started-with-privado docs in privado github repo

**Comment by ojaswa1942** [comment] 2022-09-07 09:11
Thanks for the information @SandhyaBaskaran. 
Are you also using WSL? If so, did you encounter any problems with the installation or tool usage?
We are trying to evaluate any unexpected behaviour on Windows WSL.

**Comment by tuxology** [comment] 2022-09-16 01:39
@girirajvengurlekar I was able to install privado and run this. These are the steps I followed on WSL2 on a Windows 11 machine:

```
> wsl --install -d ubuntu
$ apt update && apt upgrade
...
<install docker - instructions at https://docs.docker.com/engine/install/ubuntu/>
<add current user to docker group - https://docs.docker.com/engine/install/linux-postinstall/>
...
$ curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
$ privado scan /path/to/java/repo
```

The scan got finished and printed the results on CLI. There were issues in auto-starting the browser post that, but the CLI also gave a direct link to view results on dashboard. Everything went smooth for me.

**Comment by tuxology** [comment] 2022-09-16 11:54
Could not reproduce this one. Closing this issue and opening another one for another bur related to WSL

**Closed by tuxology** 2022-09-16 11:54 UTC
Labels: bug, cli
